export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --color=bg+:#2f3546 \
  --color=bg:#0f1215 \
  --color=border:#729dd2 \
  --color=fg:#e7eaee \
  --color=gutter:#0f1215 \
  --color=header:#ffa064 \
  --color=hl+:#ffa064 \
  --color=hl:#ffa064 \
  --color=info:#545c7e \
  --color=marker:#b2a3ff \
  --color=pointer:#b2a3ff \
  --color=prompt:#ffa064 \
  --color=query:#e7eaee:regular \
  --color=scrollbar:#729dd2 \
  --color=separator:#ffa064 \
  --color=spinner:#b2a3ff \
"
